apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: db-port
          
        #  volumeMounts:
        #    - name: mongodb-vol
        #      mountPath: /data/db
      #volumes:
       # - name: mongodb-vol
        #  persistentVolumeClaim:
         #   claimName: mongodb-pvc
