apiVersion: v1
kind: Service
metadata:
  name: acmeexplorersvc
  labels:
    app: acmeexplorer
spec:
  selector:
    app: acmeexplorer
  ports:
  - name: http-svc-port
    port: 8080
    targetPort: http-port
    nodePort: 30082
  type: NodePort
